name: "Test workflow"

on:
  release:
    types: ["published"]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test this workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Shortcut workflow
        uses: ./
        with:
          action: draft-release
          tag: ${{ github.event.inputs.release-tag }}
          shortcutAccessToken: ${{ secrets.SHORTCUT_ACCESS_TOKEN }}
          targetShortcutStateId: 500003738
